
spring.application.name=CGRSBackend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/cgrs_mobile
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=cgrs_secret_key_for_jwt_signing_2025_secure_256bit
